# Generated by Django 2.1.2 on 2018-12-05 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_title', models.CharField(max_length=200)),
                ('new_type', models.CharField(choices=[('A', '新闻'), ('B', '政策'), ('C', '行情'), ('D', '技术'), ('E', '快讯')], max_length=1)),
                ('new_detail', models.TextField(max_length=20000)),
                ('new_img', models.ImageField(upload_to='images/cover')),
                ('new_source', models.CharField(max_length=200)),
                ('new_pub', models.DateField(auto_now=True)),
                ('new_auth', models.CharField(max_length=100)),
                ('to_count', models.IntegerField(default=0)),
                ('look_count', models.IntegerField(default=0)),
                ('thumbup_count', models.IntegerField(default=0)),
                ('exmstatus', models.CharField(default='待审核', max_length=10)),
                ('pub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubuser', to='user.UserRegister')),
                ('thumbup_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbup', to='user.UserRegister')),
            ],
        ),
    ]
