# Generated by Django 2.1.2 on 2018-12-03 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intg_num', models.IntegerField()),
                ('intg_detail', models.CharField(max_length=100)),
                ('use_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_kind', models.IntegerField()),
                ('charge_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('comment_time', models.TimeField(auto_now=True)),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='user.UserRegister')),
            ],
        ),
    ]
