# Generated by Django 2.1.2 on 2018-12-05 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intg_num', models.IntegerField()),
                ('intg_detail', models.CharField(max_length=100)),
                ('use_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_kind', models.IntegerField()),
                ('charge_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=100)),
                ('get_or_cost', models.IntegerField()),
                ('exchange_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='exchg_user', to='user.UserRegister')),
            ],
        ),
        migrations.CreateModel(
            name='Money_Charge_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('charge_money', models.IntegerField()),
                ('charge_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_money_user', to='user.UserRegister')),
            ],
        ),
        migrations.CreateModel(
            name='NotifyRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('comment_time', models.TimeField(auto_now=True)),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='user.UserRegister')),
                ('commented_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_message', to='message.new_messages')),
            ],
        ),
    ]
